version: 2

# Build 설정
build:
  os: ubuntu-22.04  # 사용할 운영 체제를 지정합니다.
  tools:
    python: "3.8"  # Python 버전을 명확히 지정합니다.

# Python 설정
python:
  install:
    - requirements: requirements.txt

# Sphinx 설정
sphinx:
  configuration: sphinx/source/conf.py  # Sphinx 설정 파일 경로

