version: 2

# Python 설정
python:
  version: 3.8  # Python 버전을 정확히 명시합니다.
  install:
    - method: pip
      path: .
      requirements: requirements.txt

# Sphinx 설정
sphinx:
  configuration: sphinx/source/conf.py  # Sphinx 설정 파일 경로

