version: 2

python:
  version: 3.8
  install:
    - method: pip
      path: .
      requirements: requirements.txt

sphinx:
  configuration: sphinx/source/conf.py

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

